version: '3.8'

services:
  app:
    build:
      context: .
    ports:
      - "8086:80"
    volumes:
      - .:/usr/local/apache2/htdocs/

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3003:3003"
    environment:
      - REDIS_HOST=spotted-redis
    depends_on:
      - spotted-redis  

  spotted-redis:
    image: redis:alpine
    ports:
      - "6380:6380"